global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'oddex-engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['engine:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']
